package entity;
// Generated 12-jun-2017 20:21:35 by Hibernate Tools 4.3.1



/**
 * Description generated by hbm2java
 */
public class Description  implements java.io.Serializable {


     private Integer idD;
     private Integer user;
     private Integer groupc;
     private String commentary;

    public Description() {
    }

    public Description(Integer user, Integer groupc, String commentary) {
       this.user = user;
       this.groupc = groupc;
       this.commentary = commentary;
    }
   
    public Integer getIdD() {
        return this.idD;
    }
    
    public void setIdD(Integer idD) {
        this.idD = idD;
    }
    public Integer getUser() {
        return this.user;
    }
    
    public void setUser(Integer user) {
        this.user = user;
    }
    public Integer getGroupc() {
        return this.groupc;
    }
    
    public void setGroupc(Integer groupc) {
        this.groupc = groupc;
    }
    public String getCommentary() {
        return this.commentary;
    }
    
    public void setCommentary(String commentary) {
        this.commentary = commentary;
    }




}


