package entity;
// Generated 12-jun-2017 20:21:35 by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idU;
     private Integer type;
     private String name;
     private String password;
     private Integer class_;

    public User() {
    }

    public User(Integer type, String name, String password, Integer class_) {
       this.type = type;
       this.name = name;
       this.password = password;
       this.class_ = class_;
    }
   
    public Integer getIdU() {
        return this.idU;
    }
    
    public void setIdU(Integer idU) {
        this.idU = idU;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getClass_() {
        return this.class_;
    }
    
    public void setClass_(Integer class_) {
        this.class_ = class_;
    }




}


